
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import koneksi.kon;
import javax.swing.JOptionPane;


public class FormTransaksi extends javax.swing.JFrame {
    int Asuransi,Harga,Hjenis,Total,Hberat;
    
    Connection conn = kon.conn();
    Statement s;
    ResultSet rs;
    
    private void bersih(){
        tno.setText("");
        tnop.setText("");
        tnamap.setText("");
        talamatp.setText("");
        tnama.setText("");
        cprov.setSelectedIndex(0);
        tkota.setText("");
        tkecamatan.setText("");
        tkel.setText("");
        tkodep.setText("");
        thp.setText("");
        talamat.setText("");
        dtanggal.setDate(null);
        rjenis.clearSelection();
        tjml.setText("");
        tberat.setText("");
        tasuransi.setText("");
        ttot.setText("");
        tno.requestFocus();
    }
    public FormTransaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rjenis = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tkodep = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tnop = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        talamat = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        tnamap = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cprov = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tkota = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tkecamatan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tkel = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        talamatp = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        rreguler = new javax.swing.JRadioButton();
        ryes = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        tberat = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ttot = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tjml = new javax.swing.JTextField();
        Exit = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        thp = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        tasuransi = new javax.swing.JTextField();
        bhitung = new javax.swing.JButton();
        bsimpan1 = new javax.swing.JButton();
        minimsize = new javax.swing.JLabel();
        kembali = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dtanggal = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Transaksi");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("tanggal transaksi");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));
        jPanel1.add(tkodep, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, 100, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No Transaksi");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        jPanel1.add(tno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 210, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No Pengirim");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        tnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnopActionPerformed(evt);
            }
        });
        tnop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tnopKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnopKeyTyped(evt);
            }
        });
        jPanel1.add(tnop, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 210, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama Pengirim");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        talamat.setColumns(20);
        talamat.setRows(5);
        talamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(talamat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 210, 120));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alamat Pengirim");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        tnamap.setEditable(false);
        tnamap.setBackground(new java.awt.Color(153, 0, 255));
        tnamap.setForeground(new java.awt.Color(255, 255, 255));
        tnamap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(tnamap, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 210, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nama Penerima");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        cprov.setBackground(new java.awt.Color(102, 102, 255));
        cprov.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih Provinsi--", "Aceh", "Sumatera Utara", "Sumatera Barat", "Riau", "Kepulauan Riau", "Jambi", "Bengkulu", "Sumatera Selatan", "Kepulauan Bangka Belitung", "Lampung", "Banten", "DKI Jakarta", "Jawa Barat", "Jawa Tengah", "Jawa Timur", "DIY Yogyakarta", "Bali", "Nusa Tenggara Timur", "Nusa Tenggara Barat", "Kalimantan Barat", "Kalimantan Selatan", "Kalimantan Tengah", "Kalimantan Timur", "Kalimantan Utara", "Gorontalo", "Sulawesi Barat", "Sulawesi Selatan", "Sulawesi Tenggara", "Sulawesi Tengah", "Sulawesi Utara", "Maluku", "Maluku Utara", "Papua", "Papua Barat" }));
        cprov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cprovActionPerformed(evt);
            }
        });
        jPanel1.add(cprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 210, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Provinsi");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));
        jPanel1.add(tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 210, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Kota / Kabupaten");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));
        jPanel1.add(tkota, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 210, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Kecamatan");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));
        jPanel1.add(tkecamatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 210, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Kelurahan");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Kode Pos");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));
        jPanel1.add(tkel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 210, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("No. Handphone");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        talamatp.setEditable(false);
        talamatp.setBackground(new java.awt.Color(153, 0, 255));
        talamatp.setColumns(20);
        talamatp.setForeground(new java.awt.Color(255, 255, 255));
        talamatp.setRows(5);
        talamatp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jScrollPane2.setViewportView(talamatp);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 210, 120));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Alamat Penerima");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        rjenis.add(rreguler);
        rreguler.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rreguler.setForeground(new java.awt.Color(255, 255, 255));
        rreguler.setText("Reguler");
        rreguler.setOpaque(false);
        rreguler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rregulerActionPerformed(evt);
            }
        });
        jPanel1.add(rreguler, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 305, 90, 20));

        rjenis.add(ryes);
        ryes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ryes.setForeground(new java.awt.Color(255, 255, 255));
        ryes.setText("Yes");
        ryes.setOpaque(false);
        ryes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ryesActionPerformed(evt);
            }
        });
        jPanel1.add(ryes, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 305, 60, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Kg");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, -1, -1));
        jPanel1.add(tberat, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 50, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Jenis Pengiriman");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, -1));

        ttot.setEditable(false);
        ttot.setBackground(new java.awt.Color(236, 48, 236));
        ttot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ttot.setForeground(new java.awt.Color(255, 255, 255));
        ttot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(ttot, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 210, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Jumlah Barang");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));
        jPanel1.add(tjml, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 210, -1));

        Exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setText("X");
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 20, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Berat");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, -1, -1));
        jPanel1.add(thp, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 110, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Total Ongkir");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reset.png"))); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 610, 150, 50));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Asuransi");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, -1, -1));

        tasuransi.setEditable(false);
        tasuransi.setBackground(new java.awt.Color(236, 48, 236));
        tasuransi.setForeground(new java.awt.Color(255, 255, 255));
        tasuransi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(tasuransi, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 210, -1));

        bhitung.setBackground(new java.awt.Color(255, 51, 255));
        bhitung.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bhitung.setForeground(new java.awt.Color(255, 255, 255));
        bhitung.setText("Hitung");
        bhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhitungActionPerformed(evt);
            }
        });
        jPanel1.add(bhitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, 110, 40));

        bsimpan1.setBackground(new java.awt.Color(255, 51, 255));
        bsimpan1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bsimpan1.setForeground(new java.awt.Color(255, 255, 255));
        bsimpan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save_Icon_icon-icons.com_69139.png"))); // NOI18N
        bsimpan1.setText("Simpan");
        bsimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpan1ActionPerformed(evt);
            }
        });
        jPanel1.add(bsimpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 610, 150, 50));

        minimsize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        minimsize.setForeground(new java.awt.Color(255, 255, 255));
        minimsize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimsize.setText("-");
        minimsize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimsize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimsizeMouseClicked(evt);
            }
        });
        jPanel1.add(minimsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 20, 20));

        kembali.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kembali.setForeground(new java.awt.Color(255, 255, 255));
        kembali.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/kembali.png"))); // NOI18N
        kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMouseClicked(evt);
            }
        });
        jPanel1.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 650, 60, 50));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Transaksi Pengiriman T&T Express");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));
        jPanel1.add(dtanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 210, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/maxresdefault.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(953, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void minimsizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimsizeMouseClicked
        // TODO add your handling code here:
         this.setState(1);
    }//GEN-LAST:event_minimsizeMouseClicked

    private void kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseClicked
        // TODO add your handling code here:
        menu utama = new menu();
        utama.setVisible(true);
        dispose();
    }//GEN-LAST:event_kembaliMouseClicked

    private void tnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnopActionPerformed

    private void cprovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cprovActionPerformed
        // TODO add your handling code here:
        //Wilayah Pulau Sumatera
        if (cprov.getSelectedItem().equals("Aceh")) {
            Harga = 35000;
            Asuransi = 20000;
            tasuransi.setText("20000");
        }else if (cprov.getSelectedItem().equals("Sumatera Utara")){
            Harga = 30000;
            Asuransi = 20000;
            tasuransi.setText("20000");
        }else if (cprov.getSelectedItem().equals("Sumatera Barat")){
            Harga = 25000;
            Asuransi = 15000;
            tasuransi.setText("15000");
        }else if (cprov.getSelectedItem().equals("Riau")){
            Harga = 20000;
            Asuransi = 15000;
            tasuransi.setText("15000");
        }else if (cprov.getSelectedItem().equals("Kepulauan Riau")){
            Harga = 20000;
            Asuransi = 15000;
            tasuransi.setText("15000");
        }else if (cprov.getSelectedItem().equals("Jambi")){
            Harga = 20000;
            Asuransi = 15000;
            tasuransi.setText("15000");
        }else if (cprov.getSelectedItem().equals("Bengkulu")){
            Harga = 20000;
            Asuransi = 15000;
            tasuransi.setText("15000");
        }else if (cprov.getSelectedItem().equals("Sumatera Selatan")){
            Harga = 15000;
            Asuransi = 15000;
            tasuransi.setText("15000");
        }else if (cprov.getSelectedItem().equals("Kepulauan Bangka Belitung")){
            Harga = 15000;
            Asuransi = 10000;
            tasuransi.setText("10000");
        }else if (cprov.getSelectedItem().equals("Lampung")){
            Harga = 15000;
            Asuransi = 10000;
            tasuransi.setText("10000");
        }//Wilayah Pulau Jawa
        else if (cprov.getSelectedItem().equals("Banten")){
            Harga = 10000;
            Asuransi = 5000;
            tasuransi.setText("5000");
        }else if (cprov.getSelectedItem().equals("DKI Jakarta")){
            Harga = 10000;
            Asuransi = 5000;
            tasuransi.setText("5000");
        }else if (cprov.getSelectedItem().equals("Jawa Barat")){
            Harga = 15000;
            Asuransi = 10000;
            tasuransi.setText("10000");
        }else if (cprov.getSelectedItem().equals("Jawa Tengah")){
            Harga = 15000;
            Asuransi = 15000;
            tasuransi.setText("15000");
        }else if (cprov.getSelectedItem().equals("Jawa Timur")){
            Harga = 15000;
            Asuransi = 15000;
            tasuransi.setText("15000");
        }else if (cprov.getSelectedItem().equals("DIY Yogyakarta")){
            Harga = 15000;
            Asuransi = 15000;
            tasuransi.setText("15000");
        }// Wilayah Pulau Nusa Tengara
        else if (cprov.getSelectedItem().equals("Bali")){
            Harga = 20000;
            Asuransi = 15000;
            tasuransi.setText("15000");
        }else if (cprov.getSelectedItem().equals("Nusa Tenggara Timur")){
            Harga = 20000;
            Asuransi = 20000;
            tasuransi.setText("20000");
        }else if (cprov.getSelectedItem().equals("Nusa Tenggara Barat")){
            Harga = 20000;
            Asuransi = 20000;
            tasuransi.setText("20000");
        }//Wilayah Pulau Kalimantan
        else if (cprov.getSelectedItem().equals("Kalimantan Barat")){
            Harga = 25000;
            Asuransi = 15000;
            tasuransi.setText("15000");
        }else if (cprov.getSelectedItem().equals("Kalimantan Tengah")){
            Harga = 20000;
            Asuransi = 15000;
            tasuransi.setText("15000");
        }else if (cprov.getSelectedItem().equals("Kalimantan Selatan")){
            Harga = 15000;
            Asuransi = 15000;
            tasuransi.setText("15000");
        }else if (cprov.getSelectedItem().equals("Kalimantan Timur")){
            Harga = 25000;
            Asuransi = 15000;
            tasuransi.setText("15000");
        }else if (cprov.getSelectedItem().equals("Kalimantan Utara")){
            Harga = 25000;
            Asuransi = 20000;
            tasuransi.setText("20000");
        }// Wilayah Pulau Sulawesi
        else if (cprov.getSelectedItem().equals("Gorontalo")){
            Harga = 25000;
            Asuransi = 20000;
            tasuransi.setText("20000");
        }else if (cprov.getSelectedItem().equals("Sulawesi Barat")){
            Harga = 20000;
            Asuransi = 20000;
            tasuransi.setText("20000");
        }else if (cprov.getSelectedItem().equals("Sulawesi Tenggara")){
            Harga = 25000;
            Asuransi = 20000;
            tasuransi.setText("20000");
        }else if (cprov.getSelectedItem().equals("Sulawesi Selatan")){
            Harga = 20000;
            Asuransi = 15000;
            tasuransi.setText("15000");
        }else if (cprov.getSelectedItem().equals("Sulawesi Tengah")){
            Harga = 20000;
            Asuransi = 15000;
            tasuransi.setText("15000");
        }else if (cprov.getSelectedItem().equals("Sulawesi Utara")){
            Harga = 25000;
            Asuransi = 25000;
            tasuransi.setText("25000");
        }//Wilayah Pulau Maluku
        else if (cprov.getSelectedItem().equals("Maluku")){
            Harga = 30000;
            Asuransi = 25000;
            tasuransi.setText("25000");
        }else if (cprov.getSelectedItem().equals("Maluku Utara")){
            Harga = 30000;
            Asuransi = 25000;
            tasuransi.setText("25000");
        }//Wilayah Pulau Papua
        else if (cprov.getSelectedItem().equals("Papua")){
            Harga = 35000;
            Asuransi = 30000;
            tasuransi.setText("30000");
        }else if (cprov.getSelectedItem().equals("Papua Barat")){
            Harga = 35000;
            Asuransi = 30000;
            tasuransi.setText("30000");
        }
    }//GEN-LAST:event_cprovActionPerformed

    private void rregulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rregulerActionPerformed
        // TODO add your handling code here:
        if (rreguler.isSelected()) {
           Hjenis = 10000;
        }
    }//GEN-LAST:event_rregulerActionPerformed

    private void ryesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ryesActionPerformed
        // TODO add your handling code here:
        if (ryes.isSelected()) {
            Hjenis = 20000;
        }
    }//GEN-LAST:event_ryesActionPerformed

    private void bhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhitungActionPerformed
        // TODO add your handling code here:
        int jumlah = Integer.parseInt(tjml.getText());
        int berat = Integer.parseInt(tberat.getText());
        if (berat == 1 || berat <= 5) {
            Hberat = 5000;
            Total = (Harga + Hjenis + Hberat + Asuransi) * jumlah;
        }else if ( berat > 5) {
            Hberat = 8000;
            Total = (Harga + Hjenis + Hberat + Asuransi) * jumlah;
        }else {
            Hberat = 0;
            Total = (Harga + Hjenis + Hberat + Asuransi) * jumlah;
        }
        ttot.setText(String.valueOf(Total));
    }//GEN-LAST:event_bhitungActionPerformed

    private void tnopKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnopKeyPressed
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM kostumer WHERE no_pengirim ="+"'"+tnop.getText()+"'";
            s = conn.createStatement();
            rs = s.executeQuery(sql);
            
            while(rs.next()){
                tnamap.setText(rs.getString("nama"));
                talamatp.setText(rs.getString("alamat")); 
            }
        } catch (Exception e) {
             System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tnopKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tnopKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnopKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tnopKeyTyped

    private void bsimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpan1ActionPerformed
        // TODO add your handling code here:
//         String no = tno.getText();
        String no = tno.getText();
        String nop = tnop.getText();
        String nama = tnama.getText();
        String prov = cprov.getSelectedItem().toString();
        String kota = tkota.getText();
        String kec = tkecamatan.getText();
        String kel = tkel.getText();
        String kode = tkodep.getText();
        String HP = thp.getText();
        String alamat = talamat.getText();

        dtanggal.setDateFormatString("dd MM yyyy");
        java.sql.Date tanggal;
        tanggal = new java.sql.Date(dtanggal.getDate().getTime());
        
        String Jenis = "";
         if (rreguler.isSelected()){
            Jenis = "Reguler";
        }else if (ryes.isSelected()){
            Jenis = "Yes";
        }
         
        String jumlah = tjml.getText();
        String berat = tberat.getText();
        String asuransi = tasuransi.getText();
        String total = ttot.getText();
        
         if (tno.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Mohon masukan data untuk di input","PERHATIAN", JOptionPane.WARNING_MESSAGE);
        }else{
            try {
                s = conn.createStatement();
                rs = s.executeQuery("SELECT * FROM transaksi_pengiriman WHERE no_transaksi='"+tno.getText()+"'or nama_penerima='"+tnama.getText()+"'");
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Data sudah Ada coba masukan lagi","PERHATIAN",JOptionPane.WARNING_MESSAGE);
                    tno.requestFocus();
                }else{
                    String sql = "insert into transaksi_pengiriman values('"+no+"','"+nop
                    +"','"+nama+"','"+prov+"','"+kota+"','"+kec+"','"+kel+"','"+kode+"','"
                    +alamat+"','"+HP+"','"+tanggal+"','"+jumlah+"','"+berat+"','"+Jenis+"','"+asuransi+"','"+total+"')";
                    s = conn.createStatement();
                    s.executeUpdate(sql);

                    bersih();

                    JOptionPane.showMessageDialog(null, "DATA BERHASIL DISIMPAN","SUKSES",JOptionPane.INFORMATION_MESSAGE);
                }
                s.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
         }
    }//GEN-LAST:event_bsimpan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JButton bhitung;
    private javax.swing.JButton bsimpan1;
    private javax.swing.JComboBox cprov;
    private com.toedter.calendar.JDateChooser dtanggal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel kembali;
    private javax.swing.JLabel minimsize;
    private javax.swing.ButtonGroup rjenis;
    private javax.swing.JRadioButton rreguler;
    private javax.swing.JRadioButton ryes;
    private javax.swing.JTextArea talamat;
    private javax.swing.JTextArea talamatp;
    private javax.swing.JTextField tasuransi;
    private javax.swing.JTextField tberat;
    private javax.swing.JTextField thp;
    private javax.swing.JTextField tjml;
    private javax.swing.JTextField tkecamatan;
    private javax.swing.JTextField tkel;
    private javax.swing.JTextField tkodep;
    private javax.swing.JTextField tkota;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tnamap;
    private javax.swing.JTextField tno;
    private javax.swing.JTextField tnop;
    private javax.swing.JTextField ttot;
    // End of variables declaration//GEN-END:variables
}
